sudo: required

service:
  - docker

before_install:
  - docker build -t rudolphp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rudolphp/react-test npm run test -- --coverage

after_success:
  - docker build -t rudolphp/multi-client ./client 
  - docker build -t rudolphp/multi-nginx ./nginx 
  - docker build -t rudolphp/multi-server ./server 
  - docker build -t rudolphp/multi-worker ./worker 

  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # takes images and push to docker hub
  - docker push rudolphp/multi-client
  - docker push rudolphp/multi-nginx
  - docker push rudolphp/multi-server
  - docker push rudolphp/multi-worker
